version: '3'
services:
  server:
    hostname: MAFIA
    build:
      context: .
      dockerfile: ServerDockerfile
    expose:
      - 50051/udp
    ports:
      - 50051:50051/udp
  random_player:
    build:
      context: .
      dockerfile: RandomPlayerDockerfile
    expose:
      - 50051/udp
    depends_on:
      - server
    deploy:
      replicas: 3